# Generated by Django 2.1.12 on 2019-12-26 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datacom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dba_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('main_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('main_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('tax_id', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('corp_address', models.CharField(blank=True, max_length=20, null=True)),
                ('corp_city', models.CharField(blank=True, max_length=20, null=True)),
                ('corp_state', models.CharField(blank=True, max_length=20, null=True)),
                ('corp_zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('mailing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,16}$')])),
                ('barcode', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_address', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('billing_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=50, null=True)),
                ('resale_id', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,20}$')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datacom_creator', to='employees.Employee')),
                ('customer', models.ManyToManyField(blank=True, related_name='datacom_customers', to='customers.Customer')),
                ('employee', models.ManyToManyField(blank=True, related_name='datacom_employees', to='employees.Employee')),
            ],
            options={
                'ordering': ['-created_at', 'dba_name'],
            },
        ),
    ]
